---
- name: Setup Docker Compose
  hosts: "{{ target | default('no_host') }}"
  become: yes
  tasks:
    - name: Install Docker Compose
      shell: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose

    - name: Install "haveged" to prevent "docker-compose" from hanging
      # Source: https://github.com/docker/compose/issues/6678#issuecomment-494398740
      apt:
        name: haveged
        state: latest
        update_cache: true
